// 
// Decompiled by Procyon v0.5.30
// 

package org.apache.coyote;

public enum ActionCode
{
    ACK, 
    CLOSE, 
    COMMIT, 
    CLIENT_FLUSH, 
    CUSTOM, 
    RESET, 
    POST_REQUEST, 
    DISABLE_SWALLOW_INPUT, 
    REQ_HOST_ATTRIBUTE, 
    REQ_HOST_ADDR_ATTRIBUTE, 
    REQ_SSL_ATTRIBUTE, 
    REQ_SSL_CERTIFICATE, 
    REQ_REMOTEPORT_ATTRIBUTE, 
    REQ_LOCALPORT_ATTRIBUTE, 
    REQ_LOCAL_ADDR_ATTRIBUTE, 
    REQ_LOCAL_NAME_ATTRIBUTE, 
    REQ_SET_BODY_REPLAY, 
    COMET_BEGIN, 
    COMET_END, 
    AVAILABLE, 
    COMET_CLOSE, 
    COMET_SETTIMEOUT, 
    ASYNC_START, 
    ASYNC_DISPATCH, 
    ASYNC_DISPATCHED, 
    ASYNC_RUN, 
    ASYNC_COMPLETE, 
    ASYNC_TIMEOUT, 
    ASYNC_ERROR, 
    ASYNC_SETTIMEOUT, 
    ASYNC_IS_ASYNC, 
    ASYNC_IS_STARTED, 
    ASYNC_IS_DISPATCHING, 
    ASYNC_IS_TIMINGOUT, 
    ASYNC_IS_ERROR, 
    UPGRADE_TOMCAT, 
    UPGRADE;
}
